RARITY = ["TROPHY ROAD", "RARE", "SUPER RARE", "EPIC", "MYTHIC", "LEGENDARY"]

OFFICIAL_CLASS = ['FIGHTER',
                  'SHARPSHOOTER',
                  'HEAVYWEIGHT',
                  'THROWER',
                  'HEALER',
                  'DASHING ASSASSIN',
                  'SKIRMISHER',
                  'SUPPORT',
                  'TOXIC ASSASSIN',
                  'STEALTHY ASSASSIN',
                  'BATTER',
                  'SNIPER']

BRAWLER_INFO = {'SHELLY': {'id': 16000000,
                           'name': 'SHELLY',
                           'rarity': 'TROPHY ROAD',
                           'starPowers': [{'id': 23000076, 'name': 'Shell Shock'},
                                          {'id': 23000135, 'name': 'Band-Aid'}],
                           'imageFile': 'SHELLY.jpg',
                           'officialClass': 'FIGHTER'},
                'COLT': {'id': 16000001,
                         'name': 'COLT',
                         'rarity': 'TROPHY ROAD',
                         'starPowers': [{'id': 23000077, 'name': 'Slick Boots'},
                                        {'id': 23000138, 'name': 'Magnum Special'}],
                         'imageFile': 'COLT.jpg',
                         'officialClass': 'SHARPSHOOTER'},
                'BULL': {'id': 16000002,
                         'name': 'BULL',
                         'rarity': 'TROPHY ROAD',
                         'starPowers': [{'id': 23000078, 'name': 'Berserker'},
                                        {'id': 23000137, 'name': 'Tough Guy'}],
                         'imageFile': 'BULL.jpg',
                         'officialClass': 'HEAVYWEIGHT'},
                'BROCK': {'id': 16000003,
                          'name': 'BROCK',
                          'rarity': 'TROPHY ROAD',
                          'starPowers': [{'id': 23000079, 'name': 'Incendiary'},
                                         {'id': 23000150, 'name': 'Rocket No\n Four'}],
                          'imageFile': 'BROCK.jpg',
                          'officialClass': 'SHARPSHOOTER'},
                'RICO': {'id': 16000004,
                         'name': 'RICO',
                         'rarity': 'SUPER RARE',
                         'starPowers': [{'id': 23000080, 'name': 'Super Bouncy'},
                                        {'id': 23000156, 'name': 'Robo Retreat'}],
                         'imageFile': 'RICO.jpg',
                         'officialClass': 'SHARPSHOOTER'},
                'SPIKE': {'id': 16000005,
                          'name': 'SPIKE',
                          'rarity': 'LEGENDARY',
                          'starPowers': [{'id': 23000081, 'name': 'Fertilize'},
                                         {'id': 23000151, 'name': 'Curveball'}],
                          'imageFile': 'SPIKE.jpg',
                          'officialClass': 'SHARPSHOOTER'},
                'BARLEY': {'id': 16000006,
                           'name': 'BARLEY',
                           'rarity': 'RARE',
                           'starPowers': [{'id': 23000082, 'name': 'Medical Use'},
                                          {'id': 23000158, 'name': 'Extra Noxious'}],
                           'imageFile': 'BARLEY.jpg',
                           'officialClass': 'THROWER'},
                'JESSIE': {'id': 16000007,
                           'name': 'JESSIE',
                           'rarity': 'TROPHY ROAD',
                           'starPowers': [{'id': 23000083, 'name': 'Energize'},
                                          {'id': 23000149, 'name': 'Shocky'}],
                           'imageFile': 'JESSIE.jpg',
                           'officialClass': 'FIGHTER'},
                'NITA': {'id': 16000008,
                         'name': 'NITA',
                         'rarity': 'TROPHY ROAD',
                         'starPowers': [{'id': 23000084, 'name': 'Bear With Me'},
                                        {'id': 23000136, 'name': 'Hyper Bear'}],
                         'imageFile': 'NITA.jpg',
                         'officialClass': 'FIGHTER'},
                'DYNAMIKE': {'id': 16000009,
                             'name': 'DYNAMIKE',
                             'rarity': 'TROPHY ROAD',
                             'starPowers': [{'id': 23000085, 'name': 'Dyna-Jump'},
                                            {'id': 23000155, 'name': 'Demolition'}],
                             'imageFile': 'DYNAMIKE.jpg',
                             'officialClass': 'THROWER'},
                'EL PRIMO': {'id': 16000010,
                             'name': 'EL PRIMO',
                             'rarity': 'RARE',
                             'starPowers': [{'id': 23000086, 'name': 'El Fuego'},
                                            {'id': 23000140, 'name': 'Meteor Rush'}],
                             'imageFile': 'EL_PRIMO.jpg',
                             'officialClass': 'HEAVYWEIGHT'},
                'MORTIS': {'id': 16000011,
                           'name': 'MORTIS',
                           'rarity': 'MYTHIC',
                           'starPowers': [{'id': 23000087, 'name': 'Creepy Harvest'},
                                          {'id': 23000154, 'name': 'Coiled Snake'}],
                           'imageFile': 'MORTIS.jpg',
                           'officialClass': 'DASHING ASSASSIN'},
                'CROW': {'id': 16000012,
                         'name': 'CROW',
                         'rarity': 'LEGENDARY',
                         'starPowers': [{'id': 23000088, 'name': 'Extra Toxic'},
                                        {'id': 23000143, 'name': 'Carrion Crow'}],
                         'imageFile': 'CROW.jpg',
                         'officialClass': 'TOXIC ASSASSIN'},
                'POCO': {'id': 16000013,
                         'name': 'POCO',
                         'rarity': 'RARE',
                         'starPowers': [{'id': 23000089, 'name': 'Da Capo!'},
                                        {'id': 23000144, 'name': 'Screeching Solo'}],
                         'imageFile': 'POCO.jpg',
                         'officialClass': 'HEALER'},
                'BO': {'id': 16000014,
                       'name': 'BO',
                       'rarity': 'TROPHY ROAD',
                       'starPowers': [{'id': 23000090, 'name': 'Circling Eagle'},
                                      {'id': 23000148, 'name': 'Snare a Bear'}],
                       'imageFile': 'BO.jpg',
                       'officialClass': 'FIGHTER'},
                'PIPER': {'id': 16000015,
                          'name': 'PIPER',
                          'rarity': 'EPIC',
                          'starPowers': [{'id': 23000091, 'name': 'Ambush'},
                                         {'id': 23000152, 'name': 'Snappy Sniping'}],
                          'imageFile': 'PIPER.jpg',
                          'officialClass': 'SHARPSHOOTER'},
                'PAM': {'id': 16000016,
                        'name': 'PAM',
                        'rarity': 'EPIC',
                        'starPowers': [{'id': 23000092, 'name': "Mama's Hug"},
                                       {'id': 23000139, 'name': "Mama's Squeeze"}],
                        'imageFile': 'PAM.jpg',
                        'officialClass': 'HEALER'},
                'TARA': {'id': 16000017,
                         'name': 'TARA',
                         'rarity': 'MYTHIC',
                         'starPowers': [{'id': 23000093, 'name': 'Black Portal'},
                                        {'id': 23000160, 'name': 'Healing Shade'}],
                         'imageFile': 'TARA.jpg',
                         'officialClass': 'SKIRMISHER'},
                'DARRYL': {'id': 16000018,
                           'name': 'DARRYL',
                           'rarity': 'SUPER RARE',
                           'starPowers': [{'id': 23000094, 'name': 'Steel Hoops'},
                                          {'id': 23000157, 'name': 'Rolling Reload'}],
                           'imageFile': 'DARRYL.jpg',
                           'officialClass': 'HEAVYWEIGHT'},
                'PENNY': {'id': 16000019,
                          'name': 'PENNY',
                          'rarity': 'SUPER RARE',
                          'starPowers': [{'id': 23000099, 'name': 'Last Blast'},
                                         {'id': 23000142, 'name': 'Balls of Fire'}],
                          'imageFile': 'PENNY.jpg',
                          'officialClass': 'SHARPSHOOTER'},
                'FRANK': {'id': 16000020,
                          'name': 'FRANK',
                          'rarity': 'EPIC',
                          'starPowers': [{'id': 23000104, 'name': 'Power Grab'},
                                         {'id': 23000153, 'name': 'Sponge'}],
                          'imageFile': 'FRANK.jpg',
                          'officialClass': 'HEAVYWEIGHT'},
                'GENE': {'id': 16000021,
                         'name': 'GENE',
                         'rarity': 'MYTHIC',
                         'starPowers': [{'id': 23000109, 'name': 'Magic Puffs'},
                                        {'id': 23000159, 'name': 'Spirit Slap'}],
                         'imageFile': 'GENE.jpg',
                         'officialClass': 'SUPPORT'},
                'TICK': {'id': 16000022,
                         'name': 'TICK',
                         'rarity': 'TROPHY ROAD',
                         'starPowers': [{'id': 23000114, 'name': 'Well Oiled'},
                                        {'id': 23000161, 'name': 'Automa-Tick Reload'}],
                         'imageFile': 'TICK.jpg',
                         'officialClass': 'THROWER'},
                'LEON': {'id': 16000023,
                         'name': 'LEON',
                         'rarity': 'LEGENDARY',
                         'starPowers': [{'id': 23000119, 'name': 'Smoke Trails'},
                                        {'id': 23000141, 'name': 'Invisiheal'}],
                         'imageFile': 'LEON.jpg',
                         'officialClass': 'STEALTHY ASSASSIN'},
                'ROSA': {'id': 16000024,
                         'name': 'ROSA',
                         'rarity': 'RARE',
                         'starPowers': [{'id': 23000124, 'name': 'Plant Life'},
                                        {'id': 23000147, 'name': 'Thorny Gloves'}],
                         'imageFile': 'ROSA.jpg',
                         'officialClass': 'HEAVYWEIGHT'},
                'CARL': {'id': 16000025,
                         'name': 'CARL',
                         'rarity': 'SUPER RARE',
                         'starPowers': [{'id': 23000129, 'name': 'Power Throw'},
                                        {'id': 23000145, 'name': 'Protective Pirouette'}],
                         'imageFile': 'CARL.jpg',
                         'officialClass': 'FIGHTER'},
                'BIBI': {'id': 16000026,
                         'name': 'BIBI',
                         'rarity': 'EPIC',
                         'starPowers': [{'id': 23000134, 'name': 'Home Run'},
                                        {'id': 23000146, 'name': 'Batting Stance'}],
                         'imageFile': 'BIBI.jpg',
                         'officialClass': 'BATTER'},
                '8-BIT': {'id': 16000027,
                          'name': '8-BIT',
                          'rarity': 'TROPHY ROAD',
                          'starPowers': [{'id': 23000168, 'name': 'Boosted Booster'},
                                         {'id': 23000181, 'name': 'Extra Life'}],
                          'imageFile': '8_BIT.jpg',
                          'officialClass': 'SHARPSHOOTER'},
                'SANDY': {'id': 16000028,
                          'name': 'SANDY',
                          'rarity': 'LEGENDARY',
                          'starPowers': [{'id': 23000186, 'name': 'Rude Sands'},
                                         {'id': 23000187, 'name': 'Healing Winds'}],
                          'imageFile': 'SANDY.jpg',
                          'officialClass': 'FIGHTER'},
                'BEA': {'id': 16000029,
                        'name': 'BEA',
                        'rarity': 'EPIC',
                        'starPowers': [{'id': 23000192, 'name': 'Insta Beeload'},
                                       {'id': 23000193, 'name': 'Honey Coat'}],
                        'imageFile': 'BEA.jpg',
                        'officialClass': 'SNIPER'},
                'EMZ': {'id': 16000030,
                        'name': 'EMZ',
                        'rarity': 'TROPHY ROAD',
                        'starPowers': [{'id': 23000198, 'name': 'Bad Karma'},
                                       {'id': 23000199, 'name': 'Hype'}],
                        'imageFile': 'EMZ.jpg',
                        'officialClass': 'FIGHTER'},
                'MAX': {'id': 16000032,
                        'name': 'MAX',
                        'rarity': 'MYTHIC',
                        'starPowers': [{'id': 23000210, 'name': 'Super Charged'},
                                       {'id': 23000211, 'name': "Run n' Gun"}],
                        'imageFile': 'MAX.jpg',
                        'officialClass': 'FIGHTER'}}
